### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by IgorBayerl** [IgorBayerl/chess-two#1]
- [ ] Public routes
  - [ ] Running maches
  - [ ] Ranking
  - [ ] List skins
  - [ ] List games ( the custom rules )
  - [ ] Login with firebase
  - [ ] Read only community

- [ ] Authorized routes
  - [ ] Create match
  - [ ] Join Match 
  - [ ] Create games ( custom rules )
  - [ ] Create skins
  - [ ] Buy skins
  - [ ] Comment in community
